name: Auto-version

on:

  schedule:
    - cron: "22 18 * * *" # Once a day at 18:22:00 UTC

  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string

jobs:

  auto-version:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Update version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          VERSION="${{ github.event.inputs.version }}"

          if [ -z "$VERSION" ]; then
            VERSION="$(
              curl -sSL https://api.github.com/repos/DNSControl/dnscontrol/releases/latest \
                | jq -r ".tag_name // empty"
            )"
          fi

          VERSION="$(echo "$VERSION" | sed "s/[^-_.+~0-9a-zA-Z]//g")"

          if [ -z "$VERSION" ]; then
            echo "latest upstream version: not found" >&2
            exit 0
          fi

          echo "latest upstream version: $VERSION"

          if grep -qF "$VERSION" VERSIONS; then
            echo "version exists: $VERSION"
          else
            echo "adding version: $VERSION"
            echo "$VERSION" >>VERSIONS
            sort --version-sort --reverse --output=VERSIONS VERSIONS
            git add VERSIONS
            git commit -m "Add $VERSION from upstream"
            git push
          fi

          if git tag -l "$VERSION" | grep -q "$VERSION"; then
            echo "tag exists: $VERSION"
          else
            echo "adding tag: $VERSION"
            git tag -a -m "Add $VERSION from upstream" "$VERSION"
            git push --tags
          fi
